import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";
import { Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && <Logout />}
          {!session && (
            <Link href="/login">
              <Button
                variant="contained"
                className="bg-black"
                sx={{ marginTop: 3 }}
              >
                {" "}
                Login
              </Button>
            </Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
